# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-29 01:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=500)),
                ('fp', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=100)),
                ('args', models.CharField(max_length=1000)),
                ('post', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('responded', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
