# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-29 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.IntegerField(null=True),
        ),
    ]
