# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-29 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_post_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='responded',
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.Post'),
        ),
    ]
