# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-29 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20160629_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
